const fs = require('fs');
const path = require('path');

const data = [
  { id: 1299, word: '理科', reading: 'りか', meaning: 'science' },
  { id: 1300, word: '学ぶ', reading: 'まなぶ', meaning: 'learn' },
  { id: 1301, word: '物理', reading: 'ぶつり', meaning: 'physics' },
  { id: 1302, word: '地理', reading: 'ちり', meaning: 'geography' },
  { id: 1303, word: '足し算', reading: 'たしざん', meaning: 'addition' },
  { id: 1304, word: '引き算', reading: 'ひきざん', meaning: 'subtraction' },
  { id: 1305, word: '算数', reading: 'さんすう', meaning: 'arithmetic' },
  { id: 1306, word: 'かけ算', reading: 'かけざん', meaning: 'multiplication' },
  { id: 1307, word: 'すらすら(と)', reading: 'すらすら(と)', meaning: 'smoothly' },
  { id: 1308, word: '割り算', reading: 'わりざん', meaning: 'division' },
  { id: 1309, word: '早退[する]', reading: 'そうたい', meaning: 'leaving early, leave early' },
  { id: 1310, word: '欠席[する]', reading: 'けっせき', meaning: 'absence, be absent' },
  { id: 1311, word: '〜帳', reading: '〜ちょう', meaning: '~ book' },
  { id: 1312, word: '〜届', reading: '〜とどけ', meaning: '~ form' },
  { id: 1313, word: '寝坊[する]', reading: 'ねぼう', meaning: 'oversleeping, oversleep' },
  { id: 1314, word: '遅刻[する]', reading: 'ちこく', meaning: 'tardiness, be late' },
  { id: 1315, word: 'サボる', reading: 'サボる', meaning: 'skip (class, work)' },
  { id: 1316, word: '〜書', reading: '〜しょ', meaning: '~ book' },
  { id: 1317, word: '〜部', reading: '〜ぶ', meaning: '~ club' },
  { id: 1318, word: '親友', reading: 'しんゆう', meaning: 'close friend' },
  { id: 1319, word: '仲直り[する]', reading: 'なかなおり', meaning: 'making up, make up' },
  { id: 1320, word: 'ばかな', reading: 'ばかな', meaning: 'stupid' },
  { id: 1321, word: 'ふらふらな', reading: 'ふらふらな', meaning: 'faint' },
  { id: 1322, word: 'どんなに', reading: 'どんなに', meaning: 'no matter' },
  { id: 1323, word: 'ロッカー', reading: 'ロッカー', meaning: 'locker' },
  { id: 1324, word: 'コインロッカー', reading: 'コインロッカー', meaning: 'coin locker' },
  { id: 1325, word: '教科書', reading: 'きょうかしょ', meaning: 'textbook' },
  { id: 1326, word: '持ち物', reading: 'もちもの', meaning: 'luggage, belongings' },
  { id: 1327, word: '生年月日', reading: 'せいねんがっぴ', meaning: 'birthday' },
  { id: 1328, word: 'プラスチック', reading: 'プラスチック', meaning: 'plastic' },
  { id: 1329, word: 'レポート', reading: 'レポート', meaning: 'report' },
  { id: 1330, word: '横書き', reading: 'よこがき', meaning: 'horizontal writing' },
  { id: 1331, word: '縦書き', reading: 'たてがき', meaning: 'vertical writing' },
  { id: 1332, word: '用紙', reading: 'ようし', meaning: 'paper' },
  { id: 1333, word: 'コピー用紙', reading: 'コピーようし', meaning: 'copy paper' },
  { id: 1334, word: '目次', reading: 'もくじ', meaning: 'table of contents' },
  { id: 1335, word: '父母', reading: 'ふぼ', meaning: 'parents' },
  { id: 1336, word: 'じゃんけん[する]', reading: 'じゃんけん', meaning: 'rock-paper-scissors' },
  { id: 1337, word: '思い切って', reading: 'おもいきって', meaning: 'with resolve' },
  { id: 1338, word: '引き受ける', reading: 'ひきうける', meaning: 'take on, undertake' },
  { id: 1339, word: '係', reading: 'かかり', meaning: 'charge, in charge of ~' },
  { id: 1340, word: '〜生', reading: '〜せい', meaning: '~ student' },
  { id: 1341, word: 'センター', reading: 'センター', meaning: 'center' },
  { id: 1342, word: 'グループ', reading: 'グループ', meaning: 'group' },
  { id: 1343, word: 'メンバー', reading: 'メンバー', meaning: 'member' },
  { id: 1344, word: '活動[する]', reading: 'かつどう', meaning: 'activities, do activities' },
  { id: 1345, word: '話し合う', reading: 'はなしあう', meaning: 'discuss' },
  { id: 1346, word: '話し合い', reading: 'はなしあい', meaning: 'discussion' },
  { id: 1347, word: '見学[する]', reading: 'けんがく', meaning: 'viewing, observance, view, observe' },
  { id: 1348, word: 'ばつ', reading: 'ばつ', meaning: "x, 'x' mark" },
  { id: 1349, word: 'すっかり', reading: 'すっかり', meaning: 'completely' },
  { id: 1350, word: '見直す', reading: 'みなおす', meaning: 'review' },
  { id: 1351, word: '〜学', reading: '〜がく', meaning: '~ study, ~ field' },
  { id: 1352, word: '専攻[する]', reading: 'せんこう', meaning: 'major, major in' },
  { id: 1353, word: '専門', reading: 'せんもん', meaning: 'expertise' },
  { id: 1354, word: '専門学校', reading: 'せんもんがっこう', meaning: 'vocational school' },
  { id: 1355, word: '専門家', reading: 'せんもんか', meaning: 'expert' },
  { id: 1356, word: '〜室', reading: '〜しつ', meaning: '~ room' },
  { id: 1357, word: '知識', reading: 'ちしき', meaning: 'knowledge' },
  { id: 1358, word: 'まるで', reading: 'まるで', meaning: 'just like, as if' },
  { id: 1359, word: '百科事典', reading: 'ひゃっかじてん', meaning: 'encyclopedia' },
  { id: 1360, word: '国際的な', reading: 'こくさいてきな', meaning: 'international' },
  { id: 1361, word: 'ホームステイ[する]', reading: 'ホームステイ', meaning: 'homestay, do a homestay' },
  { id: 1362, word: 'クラスメート', reading: 'クラスメート', meaning: 'classmate' },
  { id: 1363, word: '悔しい', reading: 'くやしい', meaning: 'frustrating' },
  { id: 1364, word: '時期', reading: 'じき', meaning: 'time, season' },
  { id: 1365, word: '成績', reading: 'せいせき', meaning: 'grade' },
  { id: 1366, word: '補習[する]', reading: 'ほしゅう', meaning: 'supplementary lessons, take supplementary lessons' },
  { id: 1367, word: '先輩', reading: 'せんぱい', meaning: 'senior' },
  { id: 1368, word: '後輩', reading: 'こうはい', meaning: 'junior' },
  { id: 1369, word: '〜集', reading: '〜しゅう', meaning: '~ book, ~ collection' },
  { id: 1370, word: '解く', reading: 'とく', meaning: 'solve' },
  { id: 1371, word: '〜組', reading: '〜くみ', meaning: '~ class, ~ team' },
  { id: 1372, word: '担任[する]', reading: 'たんにん', meaning: 'homeroom teacher, be in charge' },
  { id: 1373, word: 'にこにこする', reading: 'にこにこする', meaning: 'smile' },
  { id: 1374, word: '全員', reading: 'ぜんいん', meaning: 'all members' },
  { id: 1375, word: '指導[する]', reading: 'しどう', meaning: 'instructing, instruct' },
  { id: 1376, word: '指導者', reading: 'しどうしゃ', meaning: 'instructor' },
  { id: 1377, word: '教科', reading: 'きょうか', meaning: 'subject' },
  { id: 1378, word: '教師', reading: 'きょうし', meaning: 'teacher' },
  { id: 1379, word: '教授', reading: 'きょうじゅ', meaning: 'professor' },
  { id: 1380, word: '実習[する]', reading: 'じっしゅう', meaning: 'training, train' },
  { id: 1381, word: 'しあさって', reading: 'しあさって', meaning: 'three days from today' },
  { id: 1382, word: '緊張[する]', reading: 'きんちょう', meaning: 'nervousness, be nervous' },
  { id: 1383, word: '学年', reading: 'がくねん', meaning: 'school year' },
  { id: 1384, word: '貸し出し', reading: 'かしだし', meaning: 'loan, lending' },
  { id: 1385, word: '通学[する]', reading: 'つうがく', meaning: 'commuting to school, go to school' },
  { id: 1386, word: '歩道橋', reading: 'ほどうきょう', meaning: 'pedestrian bridge' },
  { id: 1387, word: '指示[する]', reading: 'しじ', meaning: 'instruction, instruct' },
  { id: 1388, word: 'いじめ', reading: 'いじめ', meaning: 'bullying' },
  { id: 1389, word: 'いじめる', reading: 'いじめる', meaning: 'bully' },
  { id: 1390, word: 'たたく', reading: 'たたく', meaning: 'hit' },
  { id: 1391, word: '引っ張る', reading: 'ひっぱる', meaning: 'pull' },
  { id: 1392, word: '疑問', reading: 'ぎもん', meaning: 'suspicion' },
  { id: 1393, word: '破る', reading: 'やぶる', meaning: 'break' },
  { id: 1394, word: '破れる', reading: 'やぶれる', meaning: 'be broken' },
  { id: 1395, word: 'カンニング[する]', reading: 'カンニング', meaning: 'cheating, cheat (on a test)' },
  { id: 1396, word: '学期', reading: 'がっき', meaning: 'semester' },
  { id: 1397, word: '読書[する]', reading: 'どくしょ', meaning: 'reading, read' },
  { id: 1398, word: '科目', reading: 'かもく', meaning: 'subject' },
  { id: 1399, word: '国語', reading: 'こくご', meaning: 'national language' },
  { id: 1400, word: '作家', reading: 'さっか', meaning: 'writer' },
  { id: 1401, word: 'レッスン[する]', reading: 'レッスン', meaning: 'lesson, take lessons' },
  { id: 1402, word: 'ゼミ', reading: 'ゼミ', meaning: 'seminar' },
  { id: 1403, word: '歓迎会', reading: 'かんげいかい', meaning: 'welcoming party' },
  { id: 1404, word: '歓迎[する]', reading: 'かんげい', meaning: 'welcoming, welcome' },
  { id: 1405, word: '延期[する]', reading: 'えんき', meaning: 'postponement, postpone' },
  { id: 1406, word: '国立', reading: 'こくりつ', meaning: 'national' },
  { id: 1407, word: '県立', reading: 'けんりつ', meaning: 'prefectural' },
  { id: 1408, word: '公立', reading: 'こうりつ', meaning: 'public' },
  { id: 1409, word: '私立', reading: 'しりつ', meaning: 'private' },
  { id: 1410, word: '大部分', reading: 'だいぶん', meaning: 'most' },
  { id: 1411, word: '給食', reading: 'きゅうしょく', meaning: 'school lunch' },
  { id: 1412, word: '当番', reading: 'とうばん', meaning: 'duty' },
  { id: 1413, word: '受験[する]', reading: 'じゅけん', meaning: 'taking an test, take an test' },
  { id: 1414, word: '受験生', reading: 'じゅけんせい', meaning: 'test taker' },
  { id: 1415, word: '〜校', reading: '〜こう', meaning: '~ school' },
  { id: 1416, word: '合格[する]', reading: 'ごうかく', meaning: 'passing, pass (a test)' },
  { id: 1417, word: '発表[する]', reading: 'はっぴょう', meaning: 'presentation, present' },
  { id: 1418, word: '直接', reading: 'ちょくせつ', meaning: 'directly' },
  { id: 1419, word: 'キャンパス', reading: 'キャンパス', meaning: 'campus' },
  { id: 1420, word: '書留', reading: 'かきとめ', meaning: 'registered mail' },
  { id: 1421, word: '受け取る', reading: 'うけとる', meaning: 'receive' },
  { id: 1422, word: '受け取り', reading: 'うけとり', meaning: 'acceptance' },
  { id: 1423, word: 'コンクール', reading: 'コンクール', meaning: 'contest' },
  { id: 1424, word: '優秀な', reading: 'ゆうしゅうな', meaning: 'excellent' },
  { id: 1425, word: '掲示板', reading: 'けいじばん', meaning: 'bulletin board' },
  { id: 1426, word: '掲示[する]', reading: 'けいじ', meaning: 'bulletin, post a bulletin' },
  { id: 1427, word: '文房具／文具', reading: 'ぶんぼうぐ／ぶんぐ', meaning: 'stationery, writing materials' },
  { id: 1428, word: '定規', reading: 'じょうぎ', meaning: 'ruler' },
  { id: 1429, word: '筆', reading: 'ふで', meaning: 'brush' },
  { id: 1430, word: '書類', reading: 'しょるい', meaning: 'document' },
  { id: 1431, word: 'ほうき', reading: 'ほうき', meaning: 'broom' },
  { id: 1432, word: '泥', reading: 'どろ', meaning: 'mud' },
  { id: 1433, word: '構いません', reading: 'かまいません', meaning: "I don't mind." },
  { id: 1434, word: '講義[する]', reading: 'こうぎ', meaning: 'lecture, give a lecture' },
  { id: 1435, word: '敬語', reading: 'けいご', meaning: 'honorific language' },
  { id: 1436, word: '初級', reading: 'しょきゅう', meaning: 'beginner level' },
  { id: 1437, word: '中級', reading: 'ちゅうきゅう', meaning: 'intermediate level' },
  { id: 1438, word: '上級', reading: 'じょうきゅう', meaning: 'advanced level' },
  { id: 1439, word: '学習[する]', reading: 'がくしゅう', meaning: 'studying, study' },
  { id: 1440, word: '〜史', reading: '〜し', meaning: '~ history' },
  { id: 1441, word: '自習[する]', reading: 'じしゅう', meaning: "self-study, study on one's own" },
  { id: 1442, word: '居眠り[する]', reading: 'いねむり', meaning: 'dozing off' },
  { id: 1443, word: '〜行', reading: '〜ぎょう', meaning: '~ line' },
  { id: 1444, word: '閉じる', reading: 'とじる', meaning: 'close' },
  { id: 1445, word: '下線', reading: 'かせん', meaning: 'underline' },
  { id: 1446, word: '引く', reading: 'ひく', meaning: 'pull' },
  { id: 1447, word: '文', reading: 'ぶん', meaning: 'sentence' },
  { id: 1448, word: '単語', reading: 'たんご', meaning: 'word' },
  { id: 1449, word: '解答用紙', reading: 'かいとうようし', meaning: 'answer sheet' },
  { id: 1450, word: '解答[する]', reading: 'かいとう', meaning: 'answer, answer' },
  { id: 1451, word: '四角(形)', reading: 'しかく(けい)', meaning: 'square (shape)' },
  { id: 1452, word: '四角い', reading: 'しかくい', meaning: 'square' },
  { id: 1453, word: '開始[する]', reading: 'かいし', meaning: 'start, start' },
  { id: 1454, word: '観察[する]', reading: 'かんさつ', meaning: 'observing, observe' },
  { id: 1455, word: 'プリント[する]', reading: 'プリント', meaning: 'handout, print' },
  { id: 1456, word: '括弧', reading: 'かっこ', meaning: 'parentheses' },
  { id: 1457, word: 'チャイム', reading: 'チャイム', meaning: 'chime' },
  { id: 1458, word: 'ストップ[する]', reading: 'ストップ', meaning: 'stopping, stop' },
  { id: 1459, word: '学割／学生割引', reading: 'がくわり／がくせいわりびき', meaning: 'student discount' },
  { id: 1460, word: '下宿', reading: 'げしゅく', meaning: 'boarding house' },
  { id: 1461, word: '男子', reading: 'だんし', meaning: 'boy' },
  { id: 1462, word: '女子', reading: 'じょし', meaning: 'girl' },
  { id: 1463, word: '授業料', reading: 'じゅぎょうりょう', meaning: 'tuition fee' },
  { id: 1464, word: '集まり', reading: 'あつまり', meaning: 'gathering' },
  { id: 1465, word: '集会', reading: 'しゅうかい', meaning: 'assembly, conference' },
  { id: 1466, word: 'いたずら[する]', reading: 'いたずら', meaning: 'prank, pull a prank, play a practical joke on' },
  { id: 1467, word: '全体', reading: 'ぜんたい', meaning: 'whole' },
  { id: 1468, word: '隠す', reading: 'かくす', meaning: 'hide' },
  { id: 1469, word: '隠れる', reading: 'かくれる', meaning: 'hide' },
  { id: 1470, word: '思いつく', reading: 'おもいつく', meaning: 'think (of something)' },
  { id: 1471, word: '思い出', reading: 'おもいで', meaning: 'memory' },
  { id: 1472, word: '行事', reading: 'ぎょうじ', meaning: 'event' },
  { id: 1473, word: '遠足', reading: 'えんそく', meaning: 'school trip' },
  { id: 1474, word: '輝く', reading: 'かがやく', meaning: 'shine' },
  { id: 1475, word: '演奏[する]', reading: 'えんそう', meaning: 'musical performance, play (music)' },
  { id: 1476, word: '印象', reading: 'いんしょう', meaning: 'impression' },
  { id: 1477, word: '印象的な', reading: 'いんしょうてきな', meaning: 'impressive' },
  { id: 1478, word: '地味な', reading: 'じみな', meaning: 'plain, simple' },
  { id: 1479, word: '前期', reading: 'ぜんき', meaning: 'first semester' },
  { id: 1480, word: '後期', reading: 'こうき', meaning: 'second semester' },
  { id: 1481, word: '合計[する]', reading: 'ごうけい', meaning: 'sum total, total' },
  { id: 1482, word: '時間割', reading: 'じかんわり', meaning: 'schedule, timetable' },
  { id: 1483, word: 'シラバス', reading: 'シラバス', meaning: 'syllabus' },
  { id: 1484, word: '掘る', reading: 'ほる', meaning: 'dig' },
  { id: 1485, word: 'こける', reading: 'こける', meaning: 'trip' },
  { id: 1486, word: 'ぶつける', reading: 'ぶつける', meaning: 'bump (into)' },
  { id: 1487, word: 'ぶつかる', reading: 'ぶつかる', meaning: 'collide with' },
  { id: 1488, word: '委員', reading: 'いいん', meaning: 'committee member' },
  { id: 1489, word: '委員会', reading: 'いいんかい', meaning: 'committee' },
  { id: 1490, word: '中心', reading: 'ちゅうしん', meaning: 'center' },
  { id: 1491, word: '司会', reading: 'しかい', meaning: 'moderating' },
  { id: 1492, word: '司会者', reading: 'しかいしゃ', meaning: 'moderator, emcee' }
];

const topic = "13";
const title = "学校 School";

const getFirebaseFormat = () => {
  return data.map((item, index) => {
    return {
      "word": item.word,
      "reading": item.reading,
      "meaning": item.meaning,
      "sentence": ""
    };
  });
};

const outputDir = path.join(__dirname, 'src', 'data', 'tango_n3_raw');
if (!fs.existsSync(outputDir)) {
  fs.mkdirSync(outputDir, { recursive: true });
}

const outputFile = path.join(outputDir, 'topic' + topic + '.json');
const outputData = {
  "topic": 'Topic ' + topic + ' ' + title,
  "words": getFirebaseFormat()
};

fs.writeFileSync(outputFile, JSON.stringify(outputData, null, 2), 'utf-8');
console.log('Successfully generated ' + outputFile);
