const fs = require('fs');
const path = require('path');

const data = [
  { id: 1147, word: '旅行', reading: 'りょこう', meaning: 'travel', sentence: '私は芸術が好きだ。旅行に行ったときは、よく美術館や博物館に行く。' },
  { id: 1148, word: '旅', reading: 'たび', meaning: 'trip, travel', sentence: '旅をするときは、すりに気をつけないといけない。' },
  { id: 1149, word: '国内旅行', reading: 'こくないりょこう', meaning: 'domestic travel' },
  { id: 1150, word: '海外旅行', reading: 'かいがいりょこう', meaning: 'overseas travel' },
  { id: 1151, word: '温泉', reading: 'おんせん', meaning: 'hot spring', sentence: '日本は火山が多いので、温泉が多い。温泉街にはホテルだけでなく、伝統的な旅館も多い。' },
  { id: 1152, word: '温泉街', reading: 'おんせんがい', meaning: 'hot spring town' },
  { id: 1153, word: '露天風呂', reading: 'ろてんぶろ', meaning: 'open-air bath' },
  { id: 1154, word: '火山', reading: 'かざん', meaning: 'volcano' },
  { id: 1155, word: '旅館', reading: 'りょかん', meaning: 'Japanese inn' },
  { id: 1156, word: '裸', reading: 'はだか', meaning: 'naked', sentence: '温泉は世界中で人気があるが、裸や肌を見られるのが恥ずかしいという人もいる。' },
  { id: 1157, word: '肌', reading: 'はだ', meaning: 'skin' },
  { id: 1158, word: '芸術', reading: 'げいじゅつ', meaning: 'art' },
  { id: 1159, word: '美術館', reading: 'びじゅつかん', meaning: 'art museum' },
  { id: 1160, word: '美術', reading: 'びじゅつ', meaning: 'art' },
  { id: 1161, word: '博物館', reading: 'はくぶつかん', meaning: 'museum' },
  { id: 1162, word: '間もなく', reading: 'まもなく', meaning: 'soon, shortly', sentence: '「間もなく、発車します」というアナウンスを聞いて、ホームの電車に飛び込んだ。' },
  { id: 1163, word: '発車', reading: 'はっしゃ', meaning: 'departure, depart' },
  { id: 1164, word: 'ホーム', reading: 'ホーム', meaning: '(train) platform' },
  { id: 1165, word: 'プラットホーム', reading: 'プラットホーム', meaning: 'platform' },
  { id: 1166, word: '飛び込む', reading: 'とびこむ', meaning: 'jump in' },
  { id: 1167, word: 'ところが', reading: 'ところが', meaning: 'however', sentence: 'ところが、その電車は特急で、降りる駅で停車せず、通過してしまった。' },
  { id: 1168, word: '停車', reading: 'ていしゃ', meaning: 'stopping, stop' },
  { id: 1169, word: '通過', reading: 'つうか', meaning: 'passing, pass' },
  { id: 1170, word: '突き当たり', reading: 'つきあたり', meaning: 'end of the road', sentence: 'A：すみません、バス乗り場を探しているんですが。\nB：バス乗り場は駅の反対側ですね。ここを左に行って、突き当たりを左に曲がって、鉄道の線路を越えないといけません。' },
  { id: 1171, word: '鉄道', reading: 'てつどう', meaning: 'railroad, railway' },
  { id: 1172, word: '線路', reading: 'せんろ', meaning: '(railway) tracks' },
  { id: 1173, word: '越える', reading: 'こえる', meaning: 'cross' },
  { id: 1174, word: 'ええと', reading: 'ええと', meaning: 'so, umm', sentence: 'A：ええと、最初に左に行って、線路を越えるんですか。\nB：私も途中まで行くので、一緒に行きましょう。ついて来てください。' },
  { id: 1175, word: 'ついて来る', reading: 'ついてくる', meaning: 'follow, come along with' },
  { id: 1176, word: 'ついて行く', reading: 'ついていく', meaning: 'go with' },
  { id: 1177, word: '日付', reading: 'ひづけ', meaning: 'date', sentence: '最近は飛行機でも、新幹線でも、スマートフォンで簡単に日付や便を変更できる。' },
  { id: 1178, word: '便', reading: 'びん', meaning: 'service (flight)' },
  { id: 1179, word: '変更', reading: 'へんこう', meaning: 'change' },
  { id: 1180, word: '到着', reading: 'とうちゃく', meaning: 'arrival, arrive', sentence: '海外に住んでいる友達がやってくるので、空港の到着ロビーまで出迎えに行った。' },
  { id: 1181, word: 'ロビー', reading: 'ロビー', meaning: 'lobby' },
  { id: 1182, word: '出迎え', reading: 'でむかえ', meaning: 'meeting, reception' },
  { id: 1183, word: 'トラブル', reading: 'トラブル', meaning: 'trouble', sentence: '飛行機のトラブルで、2時間も遅れて心配した。会えたときは抱き合って喜んだ。' },
  { id: 1184, word: '出身地', reading: 'しゅっしんち', meaning: 'where one is from, birthplace', sentence: '都会に出てきてから、出身地の言葉が通じないことがよくあった。' },
  { id: 1185, word: '出身', reading: 'しゅっしん', meaning: 'origin' },
  { id: 1186, word: '通じる', reading: 'つうじる', meaning: 'be understood, be comprehended' },
  { id: 1187, word: '方言', reading: 'ほうげん', meaning: 'dialect', sentence: '方言だと思っていない言葉が、実は方言だと分かった。' },
  { id: 1188, word: 'あと', reading: 'あと', meaning: 'more, left', sentence: 'A：出発まであと10分だよ。そろそろホームに行った方がよくない？' },
  { id: 1189, word: '待合室', reading: 'まちあいしつ', meaning: 'waiting room', sentence: 'B：まだ10分もある、だよ。待合室で休憩しようよ。' },
  { id: 1190, word: 'ぎりぎりな', reading: 'ぎりぎりな', meaning: 'grieved, just in time, barely', sentence: 'A：あなたはいつもそう。それでぎりぎりになって慌てるんだから。早くホームに行こうよ。' },
  { id: 1191, word: 'お盆', reading: 'おぼん', meaning: 'bon (Festival of the Dead)', sentence: 'お盆はたくさんの人がふるさとに向かうため、全国の道路が渋滞する。' },
  { id: 1192, word: 'ふるさと', reading: 'ふるさと', meaning: 'hometown' },
  { id: 1193, word: '向かう', reading: 'むかう', meaning: 'head to' },
  { id: 1194, word: '全国', reading: 'ぜんこく', meaning: 'nationwide' },
  { id: 1195, word: '道路', reading: 'どうろ', meaning: 'road' },
  { id: 1196, word: 'ドライブ', reading: 'ドライブ', meaning: 'driving, drive', sentence: '先日、山にドライブに行ったのだが、レジャーシーズンだったので、帰り道はすごく渋滞していた。' },
  { id: 1197, word: 'レジャー', reading: 'レジャー', meaning: 'leisure' },
  { id: 1198, word: 'シーズン', reading: 'シーズン', meaning: 'season' },
  { id: 1199, word: '渋滞', reading: 'じゅうたい', meaning: 'traffic jam, be jammed' },
  { id: 1200, word: '信号', reading: 'しんごう', meaning: 'signal', sentence: '信号も全然変わらなくて、いらいらし、疲れがたまってしまった。' },
  { id: 1201, word: '疲れ', reading: 'つかれ', meaning: 'tiredness' },
  { id: 1202, word: '時差ぼけ', reading: 'じさぼけ', meaning: 'jet lag', sentence: 'A：そういえば、海外旅行はどうだったの？\nB：楽しかったよ。でも、最初に行ったドイツは時差ぼけがひどくて、チェックインしてからずっとホテルの部屋にいて、全然観光できなかった。' },
  { id: 1203, word: '時差', reading: 'じさ', meaning: 'time difference' },
  { id: 1204, word: 'チェックイン', reading: 'チェックイン', meaning: 'check-in, check in' },
  { id: 1205, word: 'チェックアウト', reading: 'チェックアウト', meaning: 'check-out, check out' },
  { id: 1206, word: '観光', reading: 'かんこう', meaning: 'sightseeing, go sightseeing' },
  { id: 1207, word: '観光客', reading: 'かんこうきゃく', meaning: 'tourist' },
  { id: 1208, word: 'せっかく', reading: 'せっかく', meaning: 'after ~ all of that', sentence: 'A：えー、せっかく行ったのに、もったいない。' },
  { id: 1209, word: '滞在', reading: 'たいざい', meaning: 'staying, stay', sentence: 'B：うん、もうちょっと長く滞在すればよかった。' },
  { id: 1210, word: 'ビーチ', reading: 'ビーチ', meaning: 'beach', sentence: '夏にビーチへ海水浴に行くことになった。' },
  { id: 1211, word: '海水浴', reading: 'かいすいよく', meaning: 'sea water bathing' },
  { id: 1212, word: 'それで', reading: 'それで', meaning: 'so', sentence: 'それで、水着を買いに行った。' },
  { id: 1213, word: '水着', reading: 'みずぎ', meaning: 'swimsuit' },
  { id: 1214, word: '恋人', reading: 'こいびと', meaning: 'lover', sentence: '恋人と一緒に行くので、かなり迷った。' },
  { id: 1215, word: 'かなり', reading: 'かなり', meaning: 'quite' },
  { id: 1216, word: '経由', reading: 'けいゆ', meaning: 'going through, go through', sentence: 'A：この前東京に行ったとき、わざわざ金沢を経由して行ったんです。\nB：え、なんで？' },
  { id: 1217, word: '目的', reading: 'もくてき', meaning: 'purpose' },
  { id: 1218, word: '下車', reading: 'げしゃ', meaning: 'getting off, get off', sentence: 'A：JRは、目的地までの途中の駅でも自由に下車できるんです。' },
  { id: 1219, word: '城', reading: 'しろ', meaning: 'castle', sentence: 'だから、途中下車して城と庭園を見物しました。' },
  { id: 1220, word: '庭園', reading: 'ていえん', meaning: 'garden' },
  { id: 1221, word: '見物', reading: 'けんぶつ', meaning: 'seeing, see' },
  { id: 1222, word: '私鉄', reading: 'してつ', meaning: 'private railway', sentence: 'あ、私鉄は途中下車できませんよ。JRだけです。' },
  { id: 1223, word: '豊かな', reading: 'ゆたかな', meaning: 'wealthy', sentence: '豊かな国とよく言われるが、それがどういうことなのか正確に言うのは難しい。' },
  { id: 1224, word: '正確な', reading: 'せいかくな', meaning: 'precise, accurate' },
  { id: 1225, word: '建つ', reading: 'たつ', meaning: 'be built', sentence: '例えば、ビルがたくさん建っていれば豊かなのだろうか。' },
  { id: 1226, word: '建てる', reading: 'たてる', meaning: 'build' },
  { id: 1227, word: '指標', reading: 'しひょう', meaning: 'index' },
  { id: 1228, word: '指す', reading: 'さす', meaning: 'point', sentence: 'GDPという指標がよく使われ、これはその国で作られたものやサービスの合計金額を指す。' },
  { id: 1229, word: '物価', reading: 'ぶっか', meaning: 'prices', sentence: '物価も考える必要がある。' },
  { id: 1230, word: '税関', reading: 'ぜいかん', meaning: 'customs', sentence: '税関が偽物の宝石を見つけた。' },
  { id: 1231, word: '偽物', reading: 'にせもの', meaning: 'fake' },
  { id: 1232, word: '宝石', reading: 'ほうせき', meaning: 'jewelry' },
  { id: 1233, word: 'そっくりな', reading: 'そっくりな', meaning: 'just like, the splitting image of', sentence: '本物にそっくりで、ちょっと見ただけでは分からない。' },
  { id: 1234, word: 'ボート', reading: 'ボート', meaning: 'boat', sentence: 'A：この前、ボートの免許を取ったんだ。\nB：え、すごい。みんなで乗りたい。' },
  { id: 1235, word: '免許', reading: 'めんきょ', meaning: 'license' },
  { id: 1236, word: '免許証', reading: 'めんきょしょう', meaning: 'license (card)' },
  { id: 1237, word: 'エンジン', reading: 'エンジン', meaning: 'engine', sentence: 'A：いや、釣り用の、小さなエンジンがついているだけの船だよ。' },
  { id: 1238, word: 'トンネル', reading: 'トンネル', meaning: 'tunnel', sentence: 'このトンネルは、東京方面に行くときの近道である。' },
  { id: 1239, word: '方面', reading: 'ほうめん', meaning: '~ bound, heading to ~' },
  { id: 1240, word: '近道', reading: 'ちかみち', meaning: 'shortcut, take a shortcut' },
  { id: 1241, word: 'コーナー', reading: 'コーナー', meaning: 'corner, curve' },
  { id: 1242, word: '連続', reading: 'れんぞく', meaning: 'continuous, happen continuously', sentence: '昔は、コーナーが連続する山道を行く必要があった。' },
  { id: 1243, word: '岩', reading: 'いわ', meaning: 'rock', sentence: '岩が落ちている危ない道で、片道1時間もかかった。' },
  { id: 1244, word: '片道', reading: 'かたみち', meaning: 'one way' },
  { id: 1245, word: '往復', reading: 'おうふく', meaning: 'round trip, go on a round trip', sentence: '今は、20分で往復できる。' },
  { id: 1246, word: 'トラック', reading: 'トラック', meaning: 'truck', sentence: '高速道路のサービスエリアは、昔はトラックが駐車して休憩するところというイメージだったが、今は買い物が楽しめ、遊園地があるところもある。' },
  { id: 1247, word: '駐車', reading: 'ちゅうしゃ', meaning: 'parking, park' },
  { id: 1248, word: '駐車場', reading: 'ちゅうしゃじょう', meaning: 'parking lot' },
  { id: 1249, word: '遊園地', reading: 'ゆうえんち', meaning: 'amusement park' },
  { id: 1250, word: '長', reading: 'ちょう', meaning: 'long' },
  { id: 1251, word: '停留所', reading: 'ていりゅうじょ', meaning: 'bus stop', sentence: '長距離バスの停留所もあるので、車がなくても行くことができる。' },
  { id: 1252, word: '港', reading: 'みなと', meaning: 'port, harbor', sentence: 'A：なんか横浜港をクルーズ船で回りながらディナーが食べられるツアーがあるらしいよ。' },
  { id: 1253, word: '船', reading: 'ふね', meaning: 'ship' },
  { id: 1254, word: 'ツアー', reading: 'ツアー', meaning: 'tour' },
  { id: 1255, word: '定員', reading: 'ていいん', meaning: 'capacity', sentence: 'B：へえ。でも前から予約しないといけないんじゃないの。\nA：いや、定員が多いから、平日なら前日でもOKだったって。' },
  { id: 1256, word: '前日', reading: 'ぜんじつ', meaning: 'day before' },
  { id: 1257, word: '自由席', reading: 'じゆうせき', meaning: 'unreserved seat', sentence: '東海道新幹線の自由席は1号車から3号車までだ。' },
  { id: 1258, word: '〜車', reading: '〜しゃ', meaning: '~ car' },
  { id: 1259, word: '〜発', reading: '〜はつ', meaning: 'departing from ~', sentence: '東京発の「のぞみ号」の場合、前の方にある。' },
  { id: 1260, word: 'すり', reading: 'すり', meaning: 'pickpocketing', sentence: '旅をするときは、すりに気をつけないといけない。' },
  { id: 1261, word: '市場', reading: 'いちば', meaning: 'market', sentence: '特に市場など、人が多い場所は注意が必要だ。' },
  { id: 1262, word: '正面', reading: 'しょうめん', meaning: 'front', sentence: 'カバンは体の正面で持った方がいい。' },
  { id: 1263, word: '乗せる', reading: 'のせる', meaning: 'put on', sentence: 'たくさんの人を乗せたモノレールのブレーキが故障し、駅の壁にぶつかる事故が起きた。' },
  { id: 1264, word: 'モノレール', reading: 'モノレール', meaning: 'monorail' },
  { id: 1265, word: 'ブレーキ', reading: 'ブレーキ', meaning: 'brake' },
  { id: 1266, word: 'サイレン', reading: 'サイレン', meaning: 'siren', sentence: '駅ではサイレンが鳴り響き、たくさんの人が非常口に集まり、けが人が出た。' },
  { id: 1267, word: '非常口', reading: 'ひじょうぐち', meaning: 'emergency exit' },
  { id: 1268, word: '乗車券', reading: 'じょうしゃけん', meaning: 'ticket', sentence: '紙の乗車券の時代は、電車に乗った後、降りる駅が決まっていた。' },
  { id: 1269, word: '乗車', reading: 'じょうしゃ', meaning: 'riding, ride' },
  { id: 1270, word: '乗り越す', reading: 'のりこす', meaning: 'go past', sentence: '先の駅まで乗り越したときは、専用の機械に乗車券とお金を入れる必要があった。' },
  { id: 1271, word: 'タッチ', reading: 'タッチ', meaning: 'tap, touch', sentence: '今はICカードなので、タッチするだけで、どの駅でも自由に降りることができる。' },
  { id: 1272, word: 'ロケット', reading: 'ロケット', meaning: 'rocket', sentence: 'A：一回、ロケットに乗って宇宙に行ってみたいって思わない？' },
  { id: 1273, word: 'だって', reading: 'だって', meaning: 'I mean,... because', sentence: 'B：思わない。だって最初はいいけど、絶対退屈するって。' },
  { id: 1274, word: '退屈', reading: 'たいくつ', meaning: 'boredom, be bored' },
  { id: 1275, word: 'ヘリコプター', reading: 'ヘリコプター', meaning: 'helicopter', sentence: 'A：夢がないなあ。何か乗ってみたい乗り物ってないの？\nB：ヘリコプターかな。' },
  { id: 1276, word: 'サークル', reading: 'サークル', meaning: 'club', sentence: '大学のサークルのメンバーで、2泊3日の卒業旅行に行くことになった。' },
  { id: 1277, word: '〜泊', reading: '〜はく', meaning: '~ nights' },
  { id: 1278, word: 'ガイドブック', reading: 'ガイドブック', meaning: 'guidebook' },
  { id: 1279, word: 'ガイド', reading: 'ガイド', meaning: 'guide' },
  { id: 1280, word: '支度', reading: 'したく', meaning: 'preparations, prepare', sentence: 'ガイドブックを見ながら支度していると、期待が高まってきた。' },
  { id: 1281, word: '期待', reading: 'きたい', meaning: 'expectations, expect' },
  { id: 1282, word: '帰国', reading: 'きこく', meaning: 'returning home, return home', sentence: '日本に来たときは、早く帰りたいと思っていたが、帰国の日が近づくと、次第に帰りたくないという気持ちが大きくなった。' },
  { id: 1283, word: '近づく', reading: 'ちかづく', meaning: 'draw near, approach' },
  { id: 1284, word: '次第に', reading: 'しだいに', meaning: 'gradually' },
  { id: 1285, word: '草', reading: 'くさ', meaning: 'grass', sentence: 'この草は蓬といって、食べることができる。' },
  { id: 1286, word: '原料', reading: 'げんりょう', meaning: 'material, ingredient', sentence: '薬の原料にもなる。' },
  { id: 1287, word: 'ぜひとも', reading: 'ぜひとも', meaning: 'by all means', sentence: '蓬餅はスーパーでも売っているので、ぜひとも一度食べてみてほしい。' },
  { id: 1288, word: '深海', reading: 'しんかい', meaning: 'deep sea', sentence: '深海に住む珍しい魚が、偶然網にかかることがある。' },
  { id: 1289, word: '偶然', reading: 'ぐうぜん', meaning: 'by chance' },
  { id: 1290, word: '網', reading: 'あみ', meaning: 'net' },
  { id: 1291, word: '網棚', reading: 'あみだな', meaning: 'overhead luggage rack' },
  { id: 1292, word: '全〜', reading: 'ぜん〜', meaning: 'all ~', sentence: 'このホテルは全世界にある、巨大なチェーンだ。' },
  { id: 1293, word: 'チェーン', reading: 'チェーン', meaning: 'chain' },
  { id: 1294, word: 'シングル', reading: 'シングル', meaning: 'single', sentence: 'ほとんどの部屋がシングルルームという特徴がある。' },
  { id: 1295, word: 'ダブル', reading: 'ダブル', meaning: 'double' },
  { id: 1296, word: 'ツイン', reading: 'ツイン', meaning: 'twin' },
];

const topic = "12";
const title = "旅行 Travel";

const getFirebaseFormat = () => {
  return data.map((item, index) => {
    return {
      "word": item.word,
      "reading": item.reading,
      "meaning": item.meaning,
      "sentence": item.sentence || ""
    };
  });
};

const outputDir = path.join(__dirname, 'src', 'data', 'tango_n3_raw');
if (!fs.existsSync(outputDir)) {
  fs.mkdirSync(outputDir, { recursive: true });
}

const outputFile = path.join(outputDir, \`topic\${topic}.json\`);
const outputData = {
  "topic": \`Topic \${topic} \${title}\`,
  "words": getFirebaseFormat()
};

fs.writeFileSync(outputFile, JSON.stringify(outputData, null, 2), 'utf-8');
console.log(\`Successfully generated \${outputFile}\`);
