const fs = require('fs');
const path = require('path');

const data = [
  { id: 1886, word: '年齢', reading: 'ねんれい', meaning: 'age' },
  { id: 1887, word: '成人[する]', reading: 'せいじん', meaning: 'adulthood, become an adult' },
  { id: 1888, word: '成人式', reading: 'せいじんしき', meaning: 'coming-of-age ceremony' },
  { id: 1889, word: '頃', reading: 'ころ', meaning: 'around (time)' },
  { id: 1890, word: '経済', reading: 'けいざい', meaning: 'economy' },
  { id: 1891, word: '経済的', reading: 'けいざいてき', meaning: 'economic' },
  { id: 1892, word: '産業', reading: 'さんぎょう', meaning: 'industry' },
  { id: 1893, word: '縮小[する]', reading: 'しゅくしょう', meaning: 'shrinking, shrink' },
  { id: 1894, word: '長生き[する]', reading: 'ながいき', meaning: 'living long, live long' },
  { id: 1895, word: '高齢者', reading: 'こうれいしゃ', meaning: 'senior citizens' },
  { id: 1896, word: '高齢化[する]', reading: 'こうれいか', meaning: 'aging, grow old' },
  { id: 1897, word: '割合', reading: 'わりあい', meaning: 'proportion' },
  { id: 1898, word: '低下[する]', reading: 'ていか', meaning: 'descending, descend' },
  { id: 1899, word: '消費税', reading: 'しょうひぜい', meaning: 'consumption tax' },
  { id: 1900, word: '消費[する]', reading: 'しょうひ', meaning: 'consumption, consume' },
  { id: 1901, word: '〜税', reading: '〜ぜい', meaning: '〜 tax' },
  { id: 1902, word: '税金', reading: 'ぜいきん', meaning: 'tax' },
  { id: 1903, word: '制度', reading: 'せいど', meaning: 'system' },
  { id: 1904, word: '非常に', reading: 'ひじょうに', meaning: 'extremely' },
  { id: 1905, word: '緩やかな', reading: 'ゆるやかな', meaning: 'mild, calm' },
  { id: 1906, word: '変化[する]', reading: 'へんか', meaning: 'change, change' },
  { id: 1907, word: '一部', reading: 'いちぶ', meaning: 'one part' },
  { id: 1908, word: '以前', reading: 'いぜん', meaning: 'before' },
  { id: 1909, word: '現在', reading: 'げんざい', meaning: 'present' },
  { id: 1910, word: '住まい', reading: 'すまい', meaning: 'residence' },
  { id: 1911, word: '満足[する]', reading: 'まんぞく', meaning: 'satisfaction, be satisfied' },
  { id: 1912, word: '現代', reading: 'げんだい', meaning: 'present day' },
  { id: 1913, word: '現代的な', reading: 'げんだいてきな', meaning: 'contemporary' },
  { id: 1914, word: '平和な', reading: 'へいわな', meaning: 'peaceful' },
  { id: 1915, word: 'だが', reading: 'だが', meaning: 'but' },
  { id: 1916, word: '不幸な', reading: 'ふこうな', meaning: 'unhappy' },
  { id: 1917, word: '感じる', reading: 'かんじる', meaning: 'feel' },
  { id: 1918, word: '（お）年寄り', reading: '（お）としより', meaning: 'elderly person' },
  { id: 1919, word: '恐らく', reading: 'おそらく', meaning: 'probably' },
  { id: 1920, word: '首相', reading: 'しゅしょう', meaning: 'prime minister' },
  { id: 1921, word: '国民', reading: 'こくみん', meaning: 'national, citizen' },
  { id: 1922, word: '市民', reading: 'しみん', meaning: 'citizen' },
  { id: 1923, word: '例外', reading: 'れいがい', meaning: 'exception' },
  { id: 1924, word: '幸福な', reading: 'こうふくな', meaning: 'happy' },
  { id: 1925, word: '権利', reading: 'けんり', meaning: 'right' },
  { id: 1926, word: '考え', reading: 'かんがえ', meaning: 'thinking' },
  { id: 1927, word: '先日', reading: 'せんじつ', meaning: 'the other day' },
  { id: 1928, word: '選挙[する]', reading: 'せんきょ', meaning: 'election, elect' },
  { id: 1929, word: '若者', reading: 'わかもの', meaning: 'young man' },
  { id: 1930, word: '投票[する]', reading: 'とうひょう', meaning: 'voting, vote' },
  { id: 1931, word: '票', reading: 'ひょう', meaning: 'vote' },
  { id: 1932, word: '毎〜', reading: 'まい〜', meaning: 'every 〜' },
  { id: 1933, word: '解決[する]', reading: 'かいけつ', meaning: 'solving, solve' },
  { id: 1934, word: '〜法', reading: '〜ほう', meaning: '〜 method' },
  { id: 1935, word: '政府', reading: 'せいふ', meaning: 'government' },
  { id: 1936, word: '政治家', reading: 'せいじか', meaning: 'politician' },
  { id: 1937, word: '政治', reading: 'せいじ', meaning: 'politics' },
  { id: 1938, word: '青年', reading: 'せいねん', meaning: 'young man' },
  { id: 1939, word: '交流[する]', reading: 'こうりゅう', meaning: 'exchange, exchange' },
  { id: 1940, word: 'チャンス', reading: 'チャンス', meaning: 'chance' },
  { id: 1941, word: '結局', reading: 'けっきょく', meaning: 'eventually' },
  { id: 1942, word: 'アイディア／アイデア', reading: 'アイディア／アイデア', meaning: 'idea' },
  { id: 1943, word: '数える', reading: 'かぞえる', meaning: 'count' },
  { id: 1944, word: 'なんとか', reading: 'なんとか', meaning: 'somehow' },
  { id: 1945, word: '運転免許証', reading: 'うんてんめんきょしょう', meaning: 'driver\'s license' },
  { id: 1946, word: 'とっくに', reading: 'とっくに', meaning: 'already' },
  { id: 1947, word: 'お祝いする', reading: 'おいわいする', meaning: 'celebrate' },
  { id: 1948, word: '祝う', reading: 'いわう', meaning: 'celebrate' },
  { id: 1949, word: '費用', reading: 'ひよう', meaning: 'cost' },
  { id: 1950, word: '削る', reading: 'けずる', meaning: 'scrape' },
  { id: 1951, word: 'なぜなら', reading: 'なぜなら', meaning: 'because' },
  { id: 1952, word: '奨学金', reading: 'しょうがくきん', meaning: 'scholarship' },
  { id: 1953, word: '一方', reading: 'いっぽう', meaning: 'on the one hand' },
  { id: 1954, word: '学費', reading: 'がくひ', meaning: 'tuition' },
  { id: 1955, word: '仕方（が）ない', reading: 'しかた（が）ない', meaning: 'it\'s no use' },
  { id: 1956, word: '貧乏な', reading: 'びんぼうな', meaning: 'poor' },
  { id: 1957, word: '講演会', reading: 'こうえんかい', meaning: 'lecture' },
  { id: 1958, word: '講演[する]', reading: 'こうえん', meaning: 'lecture, give a lecture' },
  { id: 1959, word: '後', reading: 'のち', meaning: 'later' },
  { id: 1960, word: 'エコロジー', reading: 'エコロジー', meaning: 'ecology' },
  { id: 1961, word: '関心', reading: 'かんしん', meaning: 'interest' },
  { id: 1962, word: '一人一人', reading: 'ひとりひとり', meaning: 'one by one (people)' },
  { id: 1963, word: '行動[する]', reading: 'こうどう', meaning: 'behavior, behave' },
  { id: 1964, word: '現れる', reading: 'あらわれる', meaning: 'appear' },
  { id: 1965, word: '子育て', reading: 'こそだて', meaning: 'raising children' },
  { id: 1966, word: '最も', reading: 'もっとも', meaning: 'most' },
  { id: 1967, word: '保育園', reading: 'ほいくえん', meaning: 'nursery' },
  { id: 1968, word: '数', reading: 'かず', meaning: 'number' },
  { id: 1969, word: '増やす', reading: 'ふやす', meaning: 'increase' },
  { id: 1970, word: '結論', reading: 'けつろん', meaning: 'conclusion' },
  { id: 1971, word: '明るい', reading: 'あかるい', meaning: 'bright' },
  { id: 1972, word: '未来', reading: 'みらい', meaning: 'future' },
  { id: 1973, word: 'グラフ', reading: 'グラフ', meaning: 'graph' },
  { id: 1974, word: '老人ホーム', reading: 'ろうじんホーム', meaning: 'nursing home' },
  { id: 1975, word: '老人', reading: 'ろうじん', meaning: 'old man' },
  { id: 1976, word: '建設[する]', reading: 'けんせつ', meaning: 'building, build' },
  { id: 1977, word: '〜数', reading: '〜すう', meaning: '〜 number' },
  { id: 1978, word: '確実な', reading: 'かくじつな', meaning: 'certain' },
  { id: 1979, word: '増加[する]', reading: 'ぞうか', meaning: 'increase, increase' },
  { id: 1980, word: '減少[する]', reading: 'げんしょう', meaning: 'decrease, decrease' },
  { id: 1981, word: '通訳[する]', reading: 'つうやく', meaning: 'interpreting, interpret' },
  { id: 1982, word: 'ロボット', reading: 'ロボット', meaning: 'robot' },
  { id: 1983, word: '話題', reading: 'わだい', meaning: 'topic' },
  { id: 1984, word: '〜世紀', reading: '〜せいき', meaning: '〜 century, 〜 age' },
  { id: 1985, word: '進歩[する]', reading: 'しんぽ', meaning: 'progress, make progress' },
  { id: 1986, word: 'ますます', reading: 'ますます', meaning: 'more and more' },
  { id: 1987, word: '拡大[する]', reading: 'かくだい', meaning: 'expantion, expand' },
  { id: 1988, word: '今回', reading: 'こんかい', meaning: 'this time' },
  { id: 1989, word: '報告[する]', reading: 'ほうこく', meaning: 'report, report' },
  { id: 1990, word: '生産[する]', reading: 'せいさん', meaning: 'production, produce' },
  { id: 1991, word: '無〜', reading: 'む〜', meaning: 'no 〜' },
  { id: 1992, word: '期限', reading: 'きげん', meaning: 'time limit' },
  { id: 1993, word: 'トップ', reading: 'トップ', meaning: 'top' },
  { id: 1994, word: '無責任な', reading: 'むせきにんな', meaning: 'irresponsible' },
  { id: 1995, word: '決定[する]', reading: 'けってい', meaning: 'decision, decide' },
  { id: 1996, word: '表', reading: 'ひょう', meaning: 'table, chart' },
  { id: 1997, word: '石油', reading: 'せきゆ', meaning: 'oil' },
  { id: 1998, word: '石炭', reading: 'せきたん', meaning: 'coal' },
  { id: 1999, word: 'その他', reading: 'そのた', meaning: 'other' },
  { id: 2000, word: '資源', reading: 'しげん', meaning: 'resource' },
  { id: 2001, word: '資源ごみ', reading: 'しげんごみ', meaning: 'recyclable waste' },
  { id: 2002, word: '減る', reading: 'へる', meaning: 'decrease' },
  { id: 2003, word: 'いつまでも', reading: 'いつまでも', meaning: 'forever' },
  { id: 2004, word: 'ぴったり（と）', reading: 'ぴったり（と）', meaning: 'precisely, exactly' },
  { id: 2005, word: '状態', reading: 'じょうたい', meaning: 'status' },
  { id: 2006, word: '記入[する]', reading: 'きにゅう', meaning: 'filling out, fill out' },
  { id: 2007, word: '例', reading: 'れい', meaning: 'example' },
  { id: 2008, word: '図', reading: 'ず', meaning: 'figure' },
  { id: 2009, word: '真っ暗な', reading: 'まっくらな', meaning: 'completely dark' },
  { id: 2010, word: '残業[する]', reading: 'ざんぎょう', meaning: 'working overtime, work overtime' },
  { id: 2011, word: '取り上げる', reading: 'とりあげる', meaning: 'take up, pick up' },
  { id: 2012, word: '事件', reading: 'じけん', meaning: 'incident' },
  { id: 2013, word: '事件現場', reading: 'じけんげんば', meaning: 'incident site' },
  { id: 2014, word: '起こる', reading: 'おこる', meaning: 'occur' },
  { id: 2015, word: '以後', reading: 'いご', meaning: 'thereafter' }
];

const topic = "18";
const title = "社会 Society";

const getFirebaseFormat = () => {
  return data.map((item, index) => {
    return {
      "word": item.word,
      "reading": item.reading,
      "meaning": item.meaning,
      "sentence": ""
    };
  });
};

const outputDir = path.join(__dirname, 'src', 'data', 'tango_n3_raw');
if (!fs.existsSync(outputDir)) {
  fs.mkdirSync(outputDir, { recursive: true });
}

const outputFile = path.join(outputDir, 'topic' + topic + '.json');
const outputData = {
  "topic": 'Topic ' + topic + ' ' + title,
  "words": getFirebaseFormat()
};

fs.writeFileSync(outputFile, JSON.stringify(outputData, null, 2), 'utf-8');
console.log('Successfully generated ' + outputFile);
