import fs from 'fs';

let content = fs.readFileSync('generate_topic2_exact.js', 'utf8');

const replacements = {
  "28_1": "A：チョコレートは、<u>刻んで</u>から<ruby>溶<rt>と</rt></ruby>かしてね。\\nB：どうして？<u>いちいち</u><ruby>刻<rt>きざ</rt></ruby>まなくても<u>熱湯</u>で<ruby>溶<rt>と</rt></ruby>かせばすぐでしょ。\\nA：<ruby>低<rt>ひく</rt></ruby>い<ruby>温度<rt>おんど</rt></ruby>で<ruby>早<rt>はや</rt></ruby>く<ruby>溶<rt>と</rt></ruby>かすために<ruby>刻<rt>きざ</rt></ruby>むんだよ。<ruby>高<rt>たか</rt></ruby>い<ruby>温度<rt>おんど</rt></ruby>で<ruby>溶<rt>と</rt></ruby>かすと<ruby>味<rt>あじ</rt></ruby>が<ruby>悪<rt>わる</rt></ruby>くなるから。",
  "29_1": "A：<ruby>彼女<rt>かのじょ</rt></ruby>がおうちに<ruby>遊<rt>あそ</rt></ruby>びに<ruby>来<rt>く</rt></ruby>るの、<u>いよいよ</u><ruby>明後日<rt>あさって</rt></ruby>だね。もう<ruby>準備<rt>じゅんび</rt></ruby>はしたの？\\nB：うーん、<ruby>昼食<rt>ちゅうしょく</rt></ruby>の<u>献立</u>は<ruby>決<rt>き</rt></ruby>めたんだけど、まだ<ruby>材料<rt>ざいりょう</rt></ruby>を<u>何も</u><ruby>買<rt>か</rt></ruby>ってないんだよね。\\nA：そっか。そこの<ruby>道路<rt>どうろ</rt></ruby>を<u>隔てた</u>ところにスーパーがあるんだけど、あそこはいい<u>品</u>がそろってるよ。",
  "30_1": "A：あ、ペットボトルと<ruby>缶<rt>かん</rt></ruby>はその<ruby>袋<rt>ふくろ</rt></ruby>じゃなくて、<ruby>別<rt>べつ</rt></ruby>の<u>ごみ袋</u>に<ruby>入<rt>い</rt></ruby>れて！\\nB：え？ペットボトルは<u>プラスチック</u>だから<ruby>燃<rt>も</rt></ruby>えないごみでしょ？<ruby>同<rt>おな</rt></ruby>じ<u>分類</u>じゃないの？\\nA：<ruby>確<rt>たし</rt></ruby>かに<ruby>両方<rt>りょうほう</rt></ruby>とも<ruby>燃<rt>も</rt></ruby>えないごみだけど、<ruby>袋<rt>ふくろ</rt></ruby>は<ruby>分<rt>わ</rt></ruby>けないと。\\nB：そうなの？<u>面倒くさい</u>なあ。\\nA：<u>文句</u>を<ruby>言<rt>い</rt></ruby>わずに、<u>せっせと</u><ruby>手<rt>て</rt></ruby>を<ruby>動<rt>うご</rt></ruby>かす！",
  "30_2": "A：ごめん、お<ruby>皿<rt>さら</rt></ruby><ruby>落<rt>お</rt></ruby>として<ruby>割<rt>わ</rt></ruby>っちゃった…。<ruby>掃除<rt>そうじ</rt></ruby>するから、ほうきと<u>ちりとり</u><ruby>借<rt>か</rt></ruby>りてもいいかな？\\nB：ああ、<ruby>気<rt>き</rt></ruby>にしないで。<ruby>先<rt>さき</rt></ruby>に<ruby>水<rt>みず</rt></ruby>を<u>くん</u>できて、<u>布巾</u>で<u>じゅうたん</u>を<ruby>拭<rt>ふ</rt></ruby>いてもらえるかな？<u>放っておく</u>と<u>染み</u>になるから。",
  "31_1": "A：あれ？<ruby>量<rt>りょう</rt></ruby>が<ruby>減<rt>へ</rt></ruby>ってる<ruby>気<rt>き</rt></ruby>がするんだけど、お<ruby>父<rt>とう</rt></ruby>さん<ruby>食<rt>た</rt></ruby>べた？\\nB：<u>味見</u>してたら、<ruby>食<rt>た</rt></ruby>べすぎちゃって…。\\nA：もー！あ、ワインの<u>栓</u>も<ruby>開<rt>あ</rt></ruby>いてる！お<ruby>母<rt>かあ</rt></ruby>さんに<u>言い付ける</u>よ！",
  "32_1": "A：ケーキが<ruby>膨<rt>ふく</rt></ruby>らまない…。<u>はかり</u>も<ruby>使<rt>つか</rt></ruby>って<u>レシピ</u><ruby>通<rt>どお</rt></ruby>りの<u>分量</u>で<ruby>作<rt>つく</rt></ruby>ったのになあ。\\nB：<ruby>卵<rt>たまご</rt></ruby>とバターを<ruby>混<rt>ま</rt></ruby>ぜるとき、<ruby>卵<rt>たまご</rt></ruby>を<ruby>一度<rt>いちど</rt></ruby>に<ruby>全部<rt>ぜんぶ</rt></ruby><ruby>入<rt>い</rt></ruby>れたからかな？<ruby>一度<rt>いちど</rt></ruby>に<ruby>入<rt>い</rt></ruby>れると、うまく<ruby>混<rt>ま</rt></ruby>ざらなくて<ruby>膨<rt>ふく</rt></ruby>らみにくいらしいけど。\\nA：<u>しまった</u>！それだ！\\nB：お<ruby>菓子作<rt>かしづく</rt></ruby>りは<ruby>分量<rt>ぶんりょう</rt></ruby>だけじゃなく、<u>過程</u>も<ruby>大切<rt>たいせつ</rt></ruby>ってことだね。",
  "32_2": "A：<ruby>息子<rt>むすこ</rt></ruby>さん、<ruby>大<rt>おお</rt></ruby>きくなったね。この<ruby>間<rt>あいだ</rt></ruby>まで<u>おむつ</u><ruby>履<rt>は</rt></ruby>いてたのに。\\nB：<ruby>最近<rt>さいきん</rt></ruby>は<u>お使い</u>にも<ruby>行<rt>い</rt></ruby>ってくれるんだ。でも、まだ「<u>おんぶ</u>してー」って<ruby>言<rt>い</rt></ruby>ってくることもあるよ。",
  "33_1": "<ruby>唐揚<rt>からあ</rt></ruby>げは2<ruby>回<rt>かい</rt></ruby><u>揚げ</u>るのがおすすめだ。まず、160<ruby>度<rt>ど</rt></ruby>の<ruby>油<rt>あぶら</rt></ruby>で4<ruby>分間<rt>ふんかん</rt></ruby><ruby>揚<rt>あ</rt></ruby>げ、<ruby>油<rt>あぶら</rt></ruby>から<ruby>出<rt>だ</rt></ruby>して4<ruby>分<rt>ふん</rt></ruby><ruby>待<rt>ま</rt></ruby>つ。<ruby>待<rt>ま</rt></ruby>っている<ruby>間<rt>あいだ</rt></ruby>に<ruby>火<rt>ひ</rt></ruby>を<u>強め</u>、<ruby>油<rt>あぶら</rt></ruby>の<ruby>温度<rt>おんど</rt></ruby>を<ruby>上<rt>あ</rt></ruby>げておき、180<ruby>度<rt>ど</rt></ruby>の<ruby>油<rt>あぶら</rt></ruby>で<u>さっと</u><ruby>揚<rt>あ</rt></ruby>げれば<ruby>完成<rt>かんせい</rt></ruby>だ。<ruby>特別<rt>とくべつ</rt></ruby>な<u>味付け</u>をしなくても、この<u>手間</u>でおいしくなる。",
  "34_1": "A：そのカレー、<u>保温</u><ruby>調理<rt>ちょうり</rt></ruby>で<ruby>作<rt>つく</rt></ruby>ってみたんだけど、どうかな？\\nB：おいしいよ。<ruby>何<rt>なに</rt></ruby>か<ruby>特別<rt>とくべつ</rt></ruby>な<u>器具</u>を<ruby>使<rt>つか</rt></ruby>ったの？\\nA：ううん、<ruby>使<rt>つか</rt></ruby>ったのは<u>タイマー</u>くらい。まず、<ruby>普段<rt>ふだん</rt></ruby>と<ruby>同<rt>おな</rt></ruby>じように<u>熱した</u><ruby>鍋<rt>なべ</rt></ruby>で<ruby>具材<rt>ぐざい</rt></ruby>を<ruby>炒<rt>いた</rt></ruby>めて、<ruby>少<rt>すこ</rt></ruby>し<ruby>煮<rt>に</rt></ruby>るんだ。その<ruby>後<rt>あと</rt></ruby>、タオルで<ruby>包<rt>つつ</rt></ruby>んで30<ruby>分<rt>ぷん</rt></ruby><ruby>待<rt>ま</rt></ruby>つだけ。<ruby>母<rt>はは</rt></ruby>に<ruby>教<rt>おし</rt></ruby>えてもらったの。\\nB：へえ。<ruby>主婦<rt>しゅふ</rt></ruby>の<u>知恵</u>は<u>偉大</u>だね。",
  "35_1": "A：そのお<ruby>弁当<rt>べんとう</rt></ruby>、<ruby>自分<rt>じぶん</rt></ruby>で<ruby>作<rt>つく</rt></ruby>ったの？\\nB：そうそう。<ruby>最近<rt>さいきん</rt></ruby>、<u>節約</u>のために<u>自炊して</u>て。\\nA：<ruby>確<rt>たし</rt></ruby>かに、<ruby>自分<rt>じぶん</rt></ruby>で<ruby>作<rt>つく</rt></ruby>る<ruby>方<rt>ほう</rt></ruby>が<ruby>安<rt>やす</rt></ruby>いよね。\\nB：うん。<ruby>食事<rt>しょくじ</rt></ruby>の<ruby>量<rt>りょう</rt></ruby>も<u>コントロール</u>できるからいいよ。\\nA：でも<ruby>朝起<rt>あさお</rt></ruby>きるの<ruby>大変<rt>たいへん</rt></ruby>じゃない？\\nB：<ruby>前<rt>まえ</rt></ruby>は<ruby>早起<rt>はやお</rt></ruby>きが<ruby>苦手<rt>にがて</rt></ruby>だったけど、<ruby>食事<rt>しょくじ</rt></ruby>に<ruby>気<rt>き</rt></ruby>をつけ<ruby>始<rt>はじ</rt></ruby>めてから<ruby>毎朝<rt>まいあさ</rt></ruby><u>すっきり</u> <u>目覚められる</u>ようになったんだ。",
  "36_1": "A：どうしたの、この<ruby>部屋<rt>へや</rt></ruby>。<ruby>机<rt>つくえ</rt></ruby>の<ruby>下<rt>した</rt></ruby>には<u>紙くず</u>、キッチンには<u>洗い物</u>がいっぱい！<ruby>洗濯物<rt>せんたくもの</rt></ruby>にも<u>しわ</u>がついてる…。\\nB：<ruby>今週<rt>こんしゅう</rt></ruby><ruby>忙<rt>いそが</rt></ruby>しくて…。\\nA：<u>ルームシェア</u>してるんだよね？<ruby>一緒<rt>いっしょ</rt></ruby>に<ruby>住<rt>す</rt></ruby>んでる<ruby>人<rt>ひと</rt></ruby>は<ruby>怒<rt>おこ</rt></ruby>らないの？\\nB：<ruby>今<rt>いま</rt></ruby><ruby>旅行中<rt>りょこうちゅう</rt></ruby>で<u>不在</u>なんだ。もうすぐ<ruby>帰<rt>かえ</rt></ruby>ってくるよ。\\nA：じゃあ<ruby>早<rt>はや</rt></ruby>く<ruby>掃除<rt>そうじ</rt></ruby>しないと。ほら、その<ruby>机<rt>つくえ</rt></ruby><u>持ち上げて</u>！",
  "37_1": "A：このクッキーおいしい！<u>ねじって</u>あって、<ruby>形<rt>かたち</rt></ruby>もかわいいね！\\nB：ありがとう。<u>粗く</u> <u>砕いた</u>アーモンドを<ruby>入<rt>い</rt></ruby>れてみたんだ。<ruby>失敗<rt>しっぱい</rt></ruby>したときの<u>予備</u>にたくさん<ruby>作<rt>つく</rt></ruby>ったから、よかったらそこの<u>容器</u>に<ruby>入<rt>い</rt></ruby>れて<ruby>持<rt>も</rt></ruby>って<ruby>帰<rt>かえ</rt></ruby>って。\\nA：え、いいの？\\nB：うん。こんなに<u>大量</u>にあっても、<u>食べきれない</u>から。",
  "38_1": "<ruby>部屋<rt>へや</rt></ruby>をきれいに<u>保つ</u>ためには、<ruby>物<rt>もの</rt></ruby>を<ruby>増<rt>ふ</rt></ruby>やさないことが<ruby>重要<rt>じゅうよう</rt></ruby>だ。<ruby>物<rt>もの</rt></ruby>が<ruby>少<rt>すく</rt></ruby>ないだけで<ruby>部屋<rt>へや</rt></ruby>がきれいに<ruby>見<rt>み</rt></ruby>える。<ruby>捨<rt>す</rt></ruby>てることが<ruby>難<rt>むずか</rt></ruby>しい<ruby>場合<rt>ばあい</rt></ruby>、<ruby>使<rt>つか</rt></ruby>わない<ruby>物<rt>もの</rt></ruby>は<u>入れ物</u>にしまったり、<u>物置</u>に<ruby>入<rt>い</rt></ruby>れたりして、<ruby>物<rt>もの</rt></ruby>を<ruby>少<rt>すく</rt></ruby>なく<ruby>見<rt>み</rt></ruby>せるのも<u>有効</u>だ。<ruby>加<rt>くわ</rt></ruby>えて、<ruby>使<rt>つか</rt></ruby>ったものを<ruby>元<rt>もと</rt></ruby>の<ruby>場所<rt>ばしょ</rt></ruby>に<u>収める</u>ことも<ruby>大切<rt>たいせつ</rt></ruby>である。",
  "38_2": "A：<ruby>最近<rt>さいきん</rt></ruby>、<ruby>母<rt>はは</rt></ruby>が<ruby>家事<rt>かじ</rt></ruby>を<ruby>手伝<rt>てつだ</rt></ruby>いにうるさくて。\\nB：え？<ruby>家事<rt>かじ</rt></ruby>しないの？\\nA：<u>自ら</u><ruby>進<rt>すす</rt></ruby>んでやることはないかも。<u>炊事</u>、<ruby>洗濯<rt>せんたく</rt></ruby>、<ruby>掃除<rt>そうじ</rt></ruby>は<ruby>苦手<rt>にがて</rt></ruby>だから、<ruby>母<rt>はは</rt></ruby>に<u>任せて</u><ruby>仕事<rt>しごと</rt></ruby>に<ruby>集中<rt>しゅうちゅう</rt></ruby>したいな。\\nB：いや、できる<u>範囲</u>でやりなよ。",
  "39_1": "<ruby>最近<rt>さいきん</rt></ruby>、<ruby>家事<rt>かじ</rt></ruby>を<u>論理的に</u><ruby>行<rt>おこな</rt></ruby>う<ruby>方法<rt>ほうほう</rt></ruby>が<ruby>話題<rt>わだい</rt></ruby>になっている。これは、<ruby>家事<rt>かじ</rt></ruby>をする<ruby>前<rt>まえ</rt></ruby>に、やることや、やる<ruby>順番<rt>じゅんばん</rt></ruby>を<ruby>整理<rt>せいり</rt></ruby>しておくというものである。<ruby>作業<rt>さぎょう</rt></ruby>を<u>順々に</u><ruby>書<rt>か</rt></ruby>き<ruby>出<rt>だ</rt></ruby>すことで、<ruby>時間<rt>じかん</rt></ruby>の<ruby>無駄<rt>むだ</rt></ruby>なく<ruby>家事<rt>かじ</rt></ruby>ができるのである。また、<ruby>何<rt>なに</rt></ruby>をするべきかがはっきりするため、<ruby>夫婦<rt>ふうふ</rt></ruby>で<ruby>家事<rt>かじ</rt></ruby>を<u>分業</u>しやすくもなる。",
  "40_1": "A：お<ruby>掃除<rt>そうじ</rt></ruby><u>完了</u>！\\nB：おかげさまで<u>あっという間に</u><ruby>終<rt>お</rt></ruby>わったよ。<u>頼って</u>ばかりでごめんね。\\nA：いいよいいよ。でも、<u>かび</u>が<ruby>生<rt>は</rt></ruby>えた<ruby>服<rt>ふく</rt></ruby>が<ruby>出<rt>で</rt></ruby>てきたときは、びっくりしたな。\\nB：うっ…。<ruby>冬<rt>ふゆ</rt></ruby>は<ruby>服<rt>ふく</rt></ruby>が<ruby>乾<rt>かわ</rt></ruby>きにくいから…。\\nA：エアコンをつけた<ruby>部屋<rt>へや</rt></ruby>に<u>つるして</u>おくといいよ。<ruby>部屋<rt>へや</rt></ruby>も<ruby>乾燥<rt>かんそう</rt></ruby>しないし。",
  "41_1": "<ruby>鶏胸肉<rt>とりむねにく</rt></ruby>はいろいろな<ruby>料理<rt>りょうり</rt></ruby>に<u>応用できる</u>ので、ゆでた<ruby>鶏胸肉<rt>とりむねにく</rt></ruby>を<u>裂いて</u><ruby>冷凍保存<rt>れいとうほぞん</rt></ruby>している<ruby>人<rt>ひと</rt></ruby>も<ruby>多<rt>おお</rt></ruby>い。<ruby>鶏胸肉<rt>とりむねにく</rt></ruby>は<u>縮み</u>やすいので、<ruby>下準備<rt>したじゅんび</rt></ruby>をしておく<ruby>必要<rt>ひつよう</rt></ruby>がある。<ruby>例<rt>たと</rt></ruby>えば、<u>加熱する</u><ruby>前<rt>まえ</rt></ruby>にフォークで<ruby>刺<rt>さ</rt></ruby>したり、<u>棒</u>でたたいたりするといい。また、<ruby>袋<rt>ふくろ</rt></ruby>に<ruby>水<rt>みず</rt></ruby>と<ruby>塩<rt>しお</rt></ruby>と<ruby>砂糖<rt>さとう</rt></ruby>を<ruby>入<rt>い</rt></ruby>れ、その<ruby>中<rt>なか</rt></ruby>に<u>漬けて</u>おくのもおすすめだ。",
  "42_1": "A：そのマフラー、<ruby>新<rt>あたら</rt></ruby>しいよね？<ruby>買<rt>か</rt></ruby>ったの？\\nB：あ、これ<ruby>自分<rt>じぶん</rt></ruby>で<u>編んだ</u>んだ。\\nA：<u>器用</u>だなあ。<ruby>私<rt>わたし</rt></ruby>、<u>編み物</u>とか<u>裁縫</u>が<ruby>苦手<rt>にがて</rt></ruby>なんだよね。<ruby>中学生<rt>ちゅうがくせい</rt></ruby>のとき<u>エプロン</u><ruby>作<rt>つく</rt></ruby>ったんだけど、ポケットを<u>逆さまに</u>つけちゃって、みんなに<ruby>笑<rt>わら</rt></ruby>われちゃった。"
};

for (const [page_story, jp_text] of Object.entries(replacements)) {
  const regex = new RegExp(`(page_story:\\s*"${page_story}",\\s*\\n\\s*japanese_text:\\s*")[^"]+(")`);
  content = content.replace(regex, `$1${jp_text}$2`);
}

content = content.replace('エアコンをつかった部屋に', 'エアコンをつけた部屋に');

fs.writeFileSync('generate_topic2_exact.js', content, 'utf8');
console.log('Fixed generate_topic2_exact.js');
